### ISSUE TITLE
Ability to make our own buttons...

### ISSUE THREAD

**Issue by XeonG** [GorvGoyl/Shortcut-Menu-Bar-VSCode-Extension#28]
Something like the lines of supporting something like https://marketplace.visualstudio.com/items?itemName=hoovercj.vscode-settings-cycler   

ie the most common type of button I'd want being a toggle of some other plugins setting or command..

**Comment by XeonG** [comment]
Even better if 'toggle' buttons can get there visual status based on the command setting.. ie Active/Inactive states.

**Comment by GorvGoyl** [comment]
That seems like a good feature but a bit complex to implement. I will look into this.

**Comment by minig0d** [comment]
+1 on this idea.  I just skimmed the code of this extension, and in reality isn't it just mapping a "label" that's displayed to the user to a command?  Should be easy enough to accept this from a settings JSON obj.  By reading from the settings, it actually exponentially increases the versatility because the customizations can take place at the workspace level and can be changed accordingly.

Ex. the following extension is similar to this except in the statusbar and takes the buttons from a user provided config (and is completely customizable, including icon):
// vsc marketplace
https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-commands 
// repo for same ext if you want to browse the code
https://github.com/fabiospampinato/vscode-commands

**Comment by GitMensch** [comment]
I'd try to add this in the following way:

* add 9 "numbered" buttons at the end (using https://www.flaticon.com/de/kostenloses-icon/9_3564231 and its friends)
* instead of the `boolean` option (defaulting to false) use a `string` configuration for it (defaulting to null/empty)
* disable the icon in the menu if the configured string is null/empty
* if one of the new commands are executed: just execute the command that was configured via the setting, similar to what [vscode-commandbar's palette option](https://github.com/ppatotski/vscode-commandbar#features) does:
   * comma-separated list of commands that get executed sequentially
   * command support arguments separated by pipe (e.g. `workbench.action.tasks.runTask|My Task`)

This allows anyone to setup up to 9 (or more if you want more) self-defined actions and as those are normal settings can also be tied to the workspace.

@GorvGoyl Are you ok with this approach (or see any issue with this)? If not I'd start hacking.
@GorvGoyl Second question (which would be unrelated to my PR): would you be ok to replace the current `boolean` setting in general with the suggested `string` option? To disable a menu entrr people would then have to empty the command, to enable use the "set to default" option.

**Comment by GorvGoyl** [comment]
@GitMensch  thanks for digging, I think we can maintain both Boolean for the buttons provided by extension and String option for user-defined commands. I'm quite tied up at this time would it be possible to test this method?
I found 2 extensions doing something similar: https://github.com/AnWeber/vscode-statusbar-command , https://github.com/Gruntfuggly/activitusbar

**Comment by GitMensch** [comment]
> I'm quite tied up at this time would it be possible to test this method?

Yes, if you are fie with that approach I'd try it for user-defined ones. Depending on work-load and family I may start next week, but I'd really like to know up-front that you'd pull if the approach does work.

**Comment by GorvGoyl** [comment]
> Yes, if you are fie with that approach I'd try it for user-defined ones. Depending on work-load and family I may start next week, but I'd really like to know up-front that you'd pull if the approach does work.
I would gladly accept if it works!

**Comment by GitMensch** [comment]
> I would gladly accept if it works!

Works fine here :-) if possible I'd love to see this in a new release (including on open-vsx which is the extension provider I primarily use), possibly with the other PRs. Thanks!

**Comment by GorvGoyl** [comment]
released on vscode marketplace. Publishing on open-vsx is in pipeline
