### ISSUE TITLE
navigate back and forward icons are not aligned and not always tightly arranged

### ISSUE THREAD

**Issue by dacapoday** [GorvGoyl/Shortcut-Menu-Bar-VSCode-Extension#30]
**Bug 1**
back’s position is lower than forward’s. awkward!
![image](https://user-images.githubusercontent.com/9378047/101453118-c8507f00-3969-11eb-997e-a6c8da25be42.png)
![image](https://user-images.githubusercontent.com/9378047/101454655-4a41a780-396c-11eb-8304-7e2a8cd8740d.png)

**Bug 2**
settings icon can be inserted between back and forward. strange!
![image](https://user-images.githubusercontent.com/9378047/101453425-46ad2100-396a-11eb-83be-a31c5c8d01bb.png)

**Comment by GorvGoyl** [comment]
Ah, that's embarrassing. thank you for reporting. I will fix these in upcoming release.

**Comment by GorvGoyl** [comment]
fixed in upcoming release

**Comment by ccelik97** [comment]
Hey morphing here but I think it's relevant to this one so, now the navigate forward & backward button locations aren't consistent when we navigate back & forth between editor tabs and non-editor (settings etc) tabs. I think these two buttons showing up on the rightmost side of the displayed icon groups (because it's right aligned on that bar so these two wouldn't move around) would make more sense than them still moving around.
